### ISSUE TITLE
Logo proposal for Juke

### ISSUE THREAD

**Issue by zuurw** [sinclairnick/juke#1]
Hi, my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by sinclairnick** [comment]
Feel free to send me any designs, or make any pull requests etc. and I'd be happy to take a look and possibly update the existing logo.

**Comment by zuurw** [comment]
Hi, @sinclairnick do you have any request for the logo? do you have something in your mind?
Where can I see the existing logo?

Best Regards!

**Comment by sinclairnick** [comment]
The current logo is now at the top of the README. I'm happy too look at any logos you may upload

**Comment by zuurw** [comment]
Hi @sinclairnick, here are my designs for your project.
For the concept I get inspiried in a jukebox, music speaker and the letter J

I hope you like it.
![juke proposal](https://user-images.githubusercontent.com/40801473/43688738-8fb02e32-98e6-11e8-9851-f60e6cb40516.png)

**Comment by zuurw** [comment]
Hi @sinclairnick , did you see my logo design for this project?

Best Regards!
